NX: 1000
NY: 1000
TEXT: TJU1895
FONT: arial.ttf
SIZE: 150
RE_GRID: 3
U0: 0.05
TM: 30000  # number of time steps *
PLOT: False  # whether to plot the results
PLOT_EVERY: 100  # plot every n time steps
PLOT_AFTER: 00  # plot after n time steps
SAVE: True  # whether to save the results
SAVE_EVERY: 100  # save every n time steps
SAVE_AFTER: 0  # save after n time steps
SAVE_DSAMP: 2  # spatially downsample the output by n
SAVE_FORMAT: jnp.float16  # precision of the output